### ISSUE TITLE
MO : Improve ps_legalcompliance.php

### ISSUE THREAD

**Issue by Nobodaddy** [PrestaShop/ps_legalcompliance#22]
Just to quote myself:
_From a practical point of view it makes no sense just to make the inclusion of the revocation terms or privacy in the terms of trade comfirmation dependent from the fact, if there is any text content or not to be found in the cms "revocation terms" or "privacy". This is a conditio sine qua non, but more important is the fact that you click the option Include revocation in terms and conditions. _
And as PrestaShop always includes a dummy text here, your condition will be always true, which is nonsense!

Please see to this bugfix in my own fork: https://github.com/Nobodaddy/ps_legalcompliance-1/pull/2

**Comment by matks** [comment]
This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop. This issue is closed then.
