### ISSUE TITLE
Hook actionEmailAddAfterContent adds Content AFTER closing </body></html> Tag

### ISSUE THREAD

**Issue by hh-com** [PrestaShop/ps_legalcompliance#76]
If you add a cms page to the mails with ps_legalcompliance, the content will be insert after the closing </body></html> Tag.

1. Install ps_legalcompliance.
2. Add a cms page to a mail in the configuration.
3. Send a mail by register a new content or take an order.
4. Check the e-mail cource code.

PrestaShop version: 1.7.4

**Comment by matks** [comment]
This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop. This issue is closed then.
