### ISSUE TITLE
PS1.7.5 - ps_legalcompliance in multishop shows shippings costs link of main domain

### ISSUE THREAD

**Issue by pdkey** [PrestaShop/ps_legalcompliance#77]
The link to the shipping costs are not the right domain - in all subdomain are the from the main domain.

on the category lists in the footer works correct.

Reste, delete and a new installation without success.

**Additionnal information**
PrestaShop version: 1.7.5
PHP version: 7.2.14

**Comment by matks** [comment]
This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop. This issue is closed then.
