### ISSUE TITLE
ps_legalcompliance unit_price tax

### ISSUE THREAD

**Issue by sirius82** [PrestaShop/ps_legalcompliance#78]
Hello, because my previously post was closed and I don't know how to re-open it and I don't know if my last reply could be seen so I create a new post.

The settings :
PS **1.7.5.2** (not 1.7.6 tested to try to reproduce the issue)
ps_legalcompliance activated
tax activated.
Prices showed only to a custom group of clients (groupe name = pro)
Prices showed tax exc.
PHP 7
Theme : ZOneTheme (but tried with classic theme)

****The issue :****
On product list, unit_price is showed tax inc (bad)
On product page, unit_price is showed tax exc (good)

On product-list, unit_price is displayed by ps_legalcompliance :
    `{hook h='displayProductPriceBlock' product=$product type='unit_price'}`

On product page, unit_price is displayed by product-prices.tpl
       
     `{block name='product_unit_price'}

          {if $displayUnitPrice}

            <p class="product-unit-price sub">{l s='(%unit_price%)' d='Shop.Theme.Catalog' sprintf=['%unit_price%' => $product.unit_price_full]}</p>

          {/if}

        {/block}`

Tried with changing the theme to Classic. Same problem.

I don't know if it's linked but in ProductController.php I see :

    ` if ($product_full['unit_price_ratio'] > 0) {
            $unitPrice = ($productSettings->include_taxes) ? $product_full['price'] : $product_full['price_tax_exc'];
            $product_full['unit_price'] = $unitPrice / $product_full['unit_price_ratio'];
        }`

Thanks for your help !

**Comment by matks** [comment]
This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop. This issue is closed then.
