### ISSUE TITLE
ps_legalcompliance should show price "from" on product page too, not only in category

### ISSUE THREAD

**Issue by didi-2018** [PrestaShop/ps_legalcompliance#80]
Hello, 

this is a feature request: 

if you enable "show price from" in ps_legalcompliance it shows "from" price only in category list but NOT on product page. It should be shown on product page too. 

![image](https://user-images.githubusercontent.com/44971218/75973851-2aa9ba00-5ed6-11ea-95b8-7847fd70afa2.png)

![image](https://user-images.githubusercontent.com/44971218/75973965-50cf5a00-5ed6-11ea-8fbb-2443646e8eac.png)

![image](https://user-images.githubusercontent.com/44971218/75974058-7bb9ae00-5ed6-11ea-8b3d-3878b3de83dc.png)

![image](https://user-images.githubusercontent.com/44971218/75974152-9db33080-5ed6-11ea-9a0e-03bb34cba367.png)

a alternativ solution can also be to show the price range "from" price "to" price

![image](https://user-images.githubusercontent.com/44971218/75974313-db17be00-5ed6-11ea-8a75-ebbc9b4814a4.png)

We have in germany the PAngV (Preisangabenverordnung) (price regulation) and it says if there is an price range it HAS to be shown everywhere the price range excists. On product detail page too. So I beg you please to add the "from" label on product page too. Or the alternative solution with "from" price "to" price. 

### Specs

When the option enabled the price range underneath the price of the "Standard Combination/Attribut" displays "Price range from __the lowest combination price__ to __the highest combination price__", 
like it is here:

![image](https://user-images.githubusercontent.com/44971218/75980693-49fb1400-5ee3-11ea-83ca-0a43d835b4a7.png)

**Comment by matks** [comment]
This module has been archived, it’s no longer maintained but you still can fork it if you need it for your shop. This issue is closed then.
